name: Build and Create AppImage

# Define a manual trigger with input for version
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Install dependencies for protoc-gen-doc and set up Go environment
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    # Step 3: Install protoc-gen-doc plugin
    - name: Install protoc-gen-doc plugin
      run: |
        # Set Go modules on
        export GO111MODULE=on
        
        # Install the protoc-gen-doc plugin
        go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest

        # Add Go bin directory to PATH
        export PATH=$PATH:$(go env GOPATH)/bin

    # Step 4: Generate Markdown from the Protobuf file
    - name: Generate Protobuf Documentation
      run: |
        # Generate markdown from .proto file
        protoc --doc_out=./idl --doc_opt=markdown,protobuf.md ./idl/grpc/service.proto
        
        # Ensure the generated markdown file is added to the repository
        git add ./idl/protobuf.md
        git commit -m "Update protobuf documentation"
        git push
