name: Generate Protobuf Documentation

# Define a manual trigger with input for version
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Install dependencies for protoc-gen-doc and set up Go environment
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    # Step 3: Install protoc-gen-doc plugin
    - name: Install protoc-gen-doc plugin
      run: |
        # Set Go modules on
        export GO111MODULE=on
        
        # Install the protoc-gen-doc plugin
        go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest

        # Ensure that Go binaries are added to the PATH
        echo 'export PATH=$PATH:$(go env GOPATH)/bin' >> $HOME/.bashrc
        export PATH=$PATH:$(go env GOPATH)/bin

    # Step 4: Generate Markdown from the Protobuf file
    - name: Generate Protobuf Documentation
      run: |
        # Regenerate the shell environment to include Go binaries
        source $HOME/.bashrc

        # Generate markdown from .proto file
        protoc --doc_out=./idl --doc_opt=markdown,protobuf.md ./idl/grpc/service.proto

    # Step 5: Configure Git and commit the updated protobuf.md
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    # Step 6: Commit and push the changes
    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add ./idl/protobuf.md
        git commit -m "Update protobuf documentation"
        git push
